groups:
  - name: system-alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 0.1
        for: 1s
        labels:
          severity: warning
        annotations:
          summary: "Высокая загрузка CPU"
          description: "CPU > 80% на {{ $labels.instance }} в течение 1 мин"

      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Мало места на диске"
          description: "Доступно менее 15% на {{ $labels.instance }}"
