{
 "title": "Business Dashboard - Online Courses",
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Registered Users",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM users_db.users;"
    }
   ]
  },
  {
   "title": "Completed Lessons",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "rawSql": "\n                SELECT SUM(cnt) FROM (\n                  SELECT count(*) as cnt FROM education_db.progress_shard_1 WHERE completed = true\n                  UNION ALL\n                  SELECT count(*) FROM education_db.progress_shard_2 WHERE completed = true\n                ) AS combined;\n                "
    }
   ]
  },
  {
   "title": "Total Comments",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "rawSql": "\n                SELECT SUM(cnt) FROM (\n                  SELECT count(*) as cnt FROM activity_db.comments_shard_1\n                  UNION ALL\n                  SELECT count(*) FROM activity_db.comments_shard_2\n                ) AS combined;\n                "
    }
   ]
  }
 ]
}